export const BRAND = {
  name: "CTI Dashboard",
  shortName: "CTI",
  tagline: "Threat Intelligence",
  subtitle: "Personal Cyber Threat Intelligence Workspace",
  greeting: "Welcome back, Kanvi 👋",
  analystName: "Kanvi",
  analystRole: "Threat Intelligence Analyst",
  analystTeam: "CTI Operations",
  analystClearance: "SOC Level III",
  analystTimezone: "UTC+0",
  footer: "Powered by Cyber Threat Intelligence Automation",
  footerPersonal: "Built personally for Kanvi ❤️",
  feedCount: 12,
  maxArticleAgeHours: 48,
} as const;
